app/src/Entity/Report.php
<?php

namespace App\Entity;

use App\Repository\ReportRepository;
use Carbon\Carbon;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReportRepository::class)]
class Report
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reports')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?int $unique_pageviews = null;

    #[ORM\Column]
    private ?int $pageviews = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    public function __construct(){
        $this->created_at = Carbon::today();
        $this->updated_at = Carbon::today();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getUniquePageviews(): ?int
    {
        return $this->unique_pageviews;
    }

    public function setUniquePageviews(int $unique_pageviews): self
    {
        $this->unique_pageviews = $unique_pageviews;

        return $this;
    }

    public function getPageviews(): ?int
    {
        return $this->pageviews;
    }

    public function setPageviews(int $pageviews): self
    {
        $this->pageviews = $pageviews;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

app/src/Controller/Dashboard/DashboardController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Report;
use App\Form\User1Type;
use App\Form\UserType;
use App\Repository\ReportRepository;
use App\Service\GoogleAnalyticsService;
use App\Service\Yegob_WP_Service;
use Carbon\Carbon;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Cache\ItemInterface;

#[Route('/dashboard', name: 'app_dashboard')]
class DashboardController extends AbstractController
{

    #[Route('/', name: '_index')]
    public function index(
        Request $request,
        ReportRepository $repository
    ): Response
    {
        $user = $this->getUser();
        $selectedYear = $request->get('year', date('Y'));
        $selectedMonth = $request->get('month', date('m'));

        $reports = $repository->findReportsMonthly(
            $user->getId(),
            $selectedMonth,
            $selectedYear
        );

        $totalUniquePageViews = array_reduce(
            array_map(fn($report) => $report->getUniquePageviews(), $reports),
            fn($x, $y) => $x + $y,
            0
        );


        $totalPageViews = array_reduce(
            array_map(fn($report) => $report->getPageviews(), $reports),
            fn($x, $y) => $x + $y,
            0
        );

        $reportsByDatePeriod = [];

        // dd($reports);

        return $this->render('dashboard/index.html.twig', [
            'user' => $user,
            'isAdmin' => $user->isAdmin(),
            'reports' => $reports,
            'currentUniquePageViews' => $reports != [] ? end($reports)->getUniquePageviews() : 0,
            'totalPageviews' => $totalPageViews,
            'totalUniquePageViews' => $totalUniquePageViews
        ]);
    }

    #[Route('/links', name: '_links_page')]
    public function showArticles(
        Yegob_WP_Service $wp
    )
    {
        $cache = new FilesystemAdapter();
        $articles = $cache->get(
            'cache_article_contents',
            function(ItemInterface $item) use ($wp) {
                $item->expiresAfter(3600);
                return $wp->getPostsFromWP();
            });

        $user = $this->getUser();
        return $this->render('dashboard/articles.html.twig', [
            'articles' => $articles,
            'user' => $user,
            'isAdmin' => $user->isAdmin()
        ]);

    }

    #[Route('/account', name: '_account_page')]
    public function showProfile(Request $request): Response
    {
        $form = $this->createForm(UserType::class, $this->getUser());

        // remove roles and password
        $form->remove('roles');
        $form->remove('password');

        // Handle the form submission
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // Save the updated user information
            $user = $form->getData();
        }

        return $this->render('dashboard/account.html.twig', [
            'user' => $this->getUser(),
            'form' => $form->createView(),
            'isAdmin' => $this->getUser()->isAdmin()
        ]);
    }
}

app/templates/dashboard/account.html.twig
{% extends 'dashboard/base.html.twig' %}
{% block title %}My account{% endblock %}
{% block body %}
    <div class="col col-lg-6 col-md-12 mt-4">
        <h3>Update your informations</h3>
        <div class="card">
            <div class="card-body">
                {{ form_start(form, {'action': path('app_dashboard_account_page')}) }}
                {{ form_widget(form) }}
                <button class="btn btn-primary" type="submit">Save informations</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/dashboard/articles.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block title %}Articles - YegoB Monetization{% endblock %}

{% block body %}
    <div class="row grid">
        {% for article in articles %}
            <div class="col col-lg-4 mt-4 grid-item">
                <div class="card">
                    <img src="{{ article.jetpack_featured_media_url }}" />
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title.rendered | raw }}</h5>
                    </div>
                    <div class="card-footer">
                        <h6>Link to share:</h6>
                        <p>
                            <a href="{{ absolute_url(path('app_public_redirect', {postId: article.id, userId: user.id})) }}">
                                {{ absolute_url(path('app_public_redirect', {postId: article.id, userId: user.id})) }}
                            </a>
                        </p>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/dashboard/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css" />
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}
</head>
<body>
{% include 'dashboard/parts/header.html.twig' %}
<div class="container">
    {% block body %}{% endblock %}
</div>
{% block javascripts_footer %}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}
</body>
</html>

app/templates/dashboard/index.html.twig
{% extends 'dashboard/base.html.twig' %}
{% block title %}Dashboard - Yegob Monetization{% endblock%}
{% block body %}
    <div class="row">
        <div class="col col-lg-3  mt-3">
            <div class="card">
                <div class="card-body">
                    <p>Today's balance</p>
                    <h2>{{ currentUniquePageViews * 0.4 }} Rwf</h2>
                    <i class="fa-solid fa-sack-dollar"></i>
                </div>
            </div>
            <hr/>
            <div class="card">
                <div class="card-body">
                    <p>Today's Unique Pageviews</p>
                    <h2>{{ currentUniquePageViews }} views</h2>
                    <i class="fa-solid fa-sack-dollar"></i>
                </div>
            </div>
        </div>
        <div class="col col-lg-9  mt-3">
            <table class="table table-bordered table-striped table-hover">
                <thead class="table-light">
                <tr class="text-center">
                    <th>Date</th>
                    <th>Pageviews</th>
                    <th>Unique pageviews</th>
                    <th>Total earning</th>
                </tr>
                </thead>
                <tbody>
                {% for report in reports %}
                    <tr class="text-center">
                        <td>{{ report.updatedAt|date("d/m/Y") }}</td>
                        <td>{{ report.pageviews }}</td>
                        <td>{{ report.uniquePageviews }}</td>
                        <td>{{ report.uniquePageviews * 400/1000 }} Rwf</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr class="text-center table-dark">
                    <td><b>Total</b></td>
                    <td>{{ totalPageviews }}</td>
                    <td>{{ totalUniquePageViews }}</td>
                    <td>{{ totalUniquePageViews * 400/1000 }} Rwf</td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}